<script>
import Head from './components/Head.vue';
import Body from './components/Body.vue';
import axios from 'axios';

export default {
    created() {
        this.fetchGamesList()
    },
    components: {
        Head, Body
    },
    methods: {
        setTab(value) {
            this.tab = value;
        },
        fetchGamesList() {
            /*
             * Headers in options generated by 'rapidapi.com/digiwalls/api/mmo-games' 
             */
            const options = {
                method: 'GET',
                url: 'https://mmo-games.p.rapidapi.com/games',
                headers: {
                    'X-RapidAPI-Key': '6875f49c94msh53fa1e984a8faf3p1a30f2jsn6b0d9ecd7404',
                    'X-RapidAPI-Host': 'mmo-games.p.rapidapi.com'
                }
            }

            axios.request(options)
                .then(response => {
                    console.log(response.data)
                    this.gamesArray = response.data
                })
                .catch(console.error);
        }
    },
    data() {
        return {
            tab: 0,
            gamesArray: [],
        }
    }
}

</script>

<template>
    <div>
        <h1>Computer Games Wishlist</h1>

        <Head @filterWishList="setTab"></Head>

        <Body :selectedTab="tab" :games="gamesArray"></Body>
    </div>
</template>

<style scoped>
* {
    font-family: Arial;
}

h1 {
    text-align: center;
}
</style>
