<script>
export const listViewTab = 0;
export const wishlistTab = 1;
export const legalNotiveTab = 2;

export const singleGameViewTab = 1;


import List from './components/List.vue';
import Game from './components/Game.vue';
import axios from 'axios';

export default {
    created() {
        this.fetchGamesList()
    },
    components: {
        List, Game
    },
    methods: {
        setTab(value) {
            this.tab = value;
        },
        fetchGamesList() {
            /*
             * Headers in options generated by 'rapidapi.com/digiwalls/api/mmo-games' 
             */
            const options = {
                method: 'GET',
                url: 'https://mmo-games.p.rapidapi.com/games',
                headers: {
                    'X-RapidAPI-Key': '6875f49c94msh53fa1e984a8faf3p1a30f2jsn6b0d9ecd7404',
                    'X-RapidAPI-Host': 'mmo-games.p.rapidapi.com'
                }
            }

            axios.request(options)
                .then(response => {
                    console.log(response.data)
                    this.gamesArray = response.data
                })
                .catch(console.error);
        },
        showGame(gameId) {
            this.findGame(gameId);
            this.selectedView = singleGameViewTab;
        },
        findGame(gameId) {
            this.selectedGameIndex = 0
            while (gameId != this.gamesArray[this.selectedGameIndex].id) {
                this.selectedGameIndex++;
            }
        },
        showList() {
            this.selectedView = listViewTab
        }
    },
    data() {
        return {
            tab: listViewTab,
            gamesArray: [],
            selectedView: listViewTab,
            selectedGameIndex: 0,
            wishlist: [],
        }
    }
}

</script>

<template>
    <div>
        <h1>Computer Games Wishlist</h1>
        <v-card>
            <v-tabs fixed-tabs v-model="tab" bg-color="blue">
                <v-tab :value="0">All Games</v-tab>
                <v-tab :value="1">Wishlist</v-tab>
                <v-tab :value="2">Legal Notice</v-tab>
            </v-tabs>
            <v-window v-model="tab">
                <v-window-item :value="0">
                    <div v-show="selectedView == 0">
                        <List :games="gamesArray" @viewGame="showGame"></List>
                    </div>
                    <div v-show="selectedView == 1">
                        <Game @returnToList="showList" :gameIndex="selectedGameIndex" :games="gamesArray"></Game>
                    </div>
                </v-window-item>
                <v-window-item :value="1">
                    <h2>Wishlist</h2>
                </v-window-item>
                <v-window-item :value="2">
                    <h2>Legal Notice</h2>
                </v-window-item>
            </v-window>
        </v-card>
    </div>
</template>

<style scoped>
* {
    background-color: #0D47A1;
    font-family: Arial;
}

v-tabs {
    width: 100%;
}


h1 {
    text-align: center;
    padding: 1%;
    color: white;
}

.tabs {
    background-color: steelblue;
}
</style>
