<script>
export const listViewTab = 0;
export const wishlistTab = 1;
export const legalNotiveTab = 2;

export const singleGameViewTab = 1;


import GamesList from './components/GamesList.vue';
import SingleGame from './components/SingleGame.vue';
import WishList from './components/WishList.vue';
import axios from 'axios';

export default {
    created() {
        this.fetchGamesList()
        this.getTab()
    },
    mounted() {
        this.restoreWishlistFromCookies()
    },
    components: {
        GamesList, SingleGame, WishList
    },
    data() {
        return {
            tab: listViewTab,
            gamesArray: [],
            selectedViewAllGames: 0,
            selectedViewWishlist: 0,
            selectedGameIndexAllGames: 0,
            selectedGameIndexWishlist: 0,
            wishlistArray: []
        }
    },
    methods: {
        fetchGamesList() {
            /*
             * Headers in options generated by 'rapidapi.com/digiwalls/api/mmo-games' 
             */
            const options = {
                method: 'GET',
                url: 'https://mmo-games.p.rapidapi.com/games',
                headers: {
                    'X-RapidAPI-Key': '6875f49c94msh53fa1e984a8faf3p1a30f2jsn6b0d9ecd7404',
                    'X-RapidAPI-Host': 'mmo-games.p.rapidapi.com'
                }
            }

            axios.request(options)
                .then(response => {
                    this.gamesArray = response.data
                })
                .catch(console.error);
        },
        showGameFromList(gameId) {
            this.findGameFromList(gameId);
            this.selectedViewAllGames = singleGameViewTab;
        },
        showGameFromWishlist(gameId) {
            this.findGameFromList(gameId)
            this.selectedViewWishlist = singleGameViewTab;
        },
        findGameFromList(gameId) {
            this.selectedGameIndexAllGames = 0
            while (gameId != this.gamesArray[this.selectedGameIndexAllGames].id) {
                this.selectedGameIndexAllGames++;
            }
        },
        findGameFromWishlist(gameId) {
            this.selectedGameIndexWishlist = 0
            while (gameId != this.wishlistArray[this.selectedGameIndexWishlist].id) {
                this.selectedGameIndexWishlist++;
            }
        },
        showListAllGames() {
            this.selectedViewAllGames = listViewTab
        },
        showListWishlist() {
            this.selectedViewWishlist = listViewTab
        },
        addToWishlist(gameId) {
            let i = 0
            let existsInWishlist = false
            this.findGameFromList(gameId)
            for (i; i < this.wishlistArray.length; i++) {
                if (this.wishlistArray[i].id == gameId) {
                    existsInWishlist = true
                }
            }
            if (existsInWishlist == true) {
                alert(`The game '${this.gamesArray[i].title}' is already on the wishlist!`)
            }
            else {
                this.wishlistArray.push(this.gamesArray[this.selectedGameIndexAllGames])
            }
            sessionStorage.setItem('wishlist', JSON.stringify(this.wishlistArray))
            //jsCookie.set('wishlist', JSON.stringify(this.wishlistArray));
        },
        removeFromWishlist(gameId) {
            this.findGameFromWishlist(gameId)
            let index = this.selectedGameIndexWishlist
            this.wishlistArray.splice(index, 1)
            sessionStorage.setItem('wishlist', JSON.stringify(this.wishlistArray))
            //jsCookie.set('wishlist', JSON.stringify(this.wishlistArray));
        },

        restoreWishlistFromCookies() {
            //const cookieWishlist = jsCookie.get('wishlist');
            const cookieWishlist = sessionStorage.getItem('wishlist')
            if (cookieWishlist) {
                this.wishlistArray = JSON.parse(cookieWishlist);
            }
        },
        setTab(tabIndex) {
            sessionStorage.setItem('tab', tabIndex)
        },
        getTab() {
            this.tab = sessionStorage.getItem('tab')
        }
    }
}

</script>

<template>
    <div id="frame">
        <h1>Computer Games Wishlist</h1>
        <v-card>
            <v-tabs fixed-tabs v-model="tab" bg-color="blue">
                <v-tab :value="0" @click="setTab(0)">All Games</v-tab>
                <v-tab :value="1" @click="setTab(1)">Wishlist</v-tab>
                <v-tab :value="2" @click="setTab(2)">Legal Notice</v-tab>
            </v-tabs>
            <v-window v-model="tab">
                <v-window-item :value="0">
                    <div v-show="selectedViewAllGames == 0">
                        <GamesList :games="gamesArray" @viewGameFromAllGames="showGameFromList"
                            @addToWishlist="addToWishlist">
                        </GamesList>
                    </div>
                    <div v-show="selectedViewAllGames == 1">
                        <SingleGame @returnToList="showListAllGames" :gameIndex="selectedGameIndexAllGames"
                            :games="gamesArray">
                        </SingleGame>
                    </div>
                </v-window-item>
                <v-window-item :value="1">
                    <div v-show="selectedViewWishlist == 0">
                        <WishList :wishlist="wishlistArray" @viewGameFromWishlist="showGameFromWishlist"
                            @deleteFromWishlist="removeFromWishlist"></WishList>
                    </div>
                    <div v-show="selectedViewWishlist == 1">
                        <!--<SingleGame @returnToList="showListWishlist" :gameIndex="selectedGameIndexWishlist"
                            :games="wishlistArray">
                        </SingleGame>-->
                        <SingleGame @returnToList="showListWishlist" :gameIndex="selectedGameIndexAllGames" :games="gamesArray"></SingleGame>
                    </div>
                </v-window-item>
                <v-window-item :value="2">
                    <div id="legalNoticeTab">
                        <div id="page">

                        </div>
                    </div>
                </v-window-item>
            </v-window>
        </v-card>
    </div>
</template>

<style scoped>
* {
    background-color: #0D47A1;
    font-family: Arial;
}

v-tabs {
    width: 100%;
}


h1 {
    text-align: center;
    padding: 1%;
    color: white;
}

.tabs {
    background-color: steelblue;
}

#legalNoticeTab {
    height: 967px;
}

#page {
    background-color: lightblue;
    width: 60%;
    height: 95%;
    margin-left: auto;
    margin-right: auto;
}
</style>
