<script>
export const allGamesTab = 0;
export const wishlistTab = 1;
export const legalNotiveTab = 2;
export const listView = 0;
export const singleGameView = 1;

import GamesList from './components/GamesList.vue';
import SingleGame from './components/SingleGame.vue';
import WishList from './components/WishList.vue';
import axios from 'axios';

export default {
    created() {
        this.fetchGamesList()
        //this.getTab()
        this.restoreApplicationFromStorage()
    },
    mounted() {
        this.restoreWishlistFromCookies()
    },
    components: {
        GamesList, SingleGame, WishList
    },
    data() {
        return {
            tab: allGamesTab,
            gamesArray: [],
            wishlistArray: [],
            selectedViewAllGames: listView,
            selectedViewWishlist: listView,
            selectedGameIndexAllGames: 0,
            selectedGameIndexWishlist: 0
        }
    },
    methods: {
        fetchGamesList() {
            /*
             * Headers in options generated by 'rapidapi.com/digiwalls/api/mmo-games' 
             */
            const options = {
                method: 'GET',
                url: 'https://mmo-games.p.rapidapi.com/games',
                headers: {
                    'X-RapidAPI-Key': '6875f49c94msh53fa1e984a8faf3p1a30f2jsn6b0d9ecd7404',
                    'X-RapidAPI-Host': 'mmo-games.p.rapidapi.com'
                }
            }

            axios.request(options)
                .then(response => {
                    this.gamesArray = response.data
                })
                .catch(console.error);
        },
        showGameFromList(gameId) {
            let index = this.findGame(gameId, this.gamesArray)
            this.selectedViewAllGames = singleGameView;
            this.selectedGameIndexAllGames = index
            sessionStorage.setItem('allGamesView', singleGameView)
        },
        showGameFromWishlist(gameId) {
            let index = this.findGame(gameId, this.gamesArray)
            this.selectedViewWishlist = singleGameView;
            this.selectedGameIndexWishlist = index
            sessionStorage.setItem('wishlistView', singleGameView)
        },
        findGame(gameId, array) {
            let index = 0
            while (gameId != array[index].id) {
                index++
            }
            return index
        },
        showListAllGames() {
            this.selectedViewAllGames = listView
            sessionStorage.setItem('allGamesView', listView)
        },
        showListWishlist() {
            this.selectedViewWishlist = listView
            sessionStorage.setItem('wishlistView', listView)
        },
        addToWishlist(gameId) {
            let existsInWishlist = false
            let index = this.findGame(gameId, this.gamesArray)
            let i = 0
            for (i; i < this.wishlistArray.length; i++) {
                if (this.wishlistArray[i].id == gameId) {
                    existsInWishlist = true
                }
            }
            if (existsInWishlist == true) {
                alert(`The game '${this.gamesArray[i].title}' is already on the wishlist!`)
            }
            else {
                this.wishlistArray.push(this.gamesArray[index])
            }
            sessionStorage.setItem('wishlist', JSON.stringify(this.wishlistArray))
        },
        removeFromWishlist(gameId) {
            let index = this.findGame(gameId, this.wishlistArray)
            this.wishlistArray.splice(index, 1)
            sessionStorage.setItem('wishlist', JSON.stringify(this.wishlistArray))
        },

        restoreWishlistFromCookies() {
            const cookieWishlist = sessionStorage.getItem('wishlist')
            if (cookieWishlist) {
                this.wishlistArray = JSON.parse(cookieWishlist);
            }
        },
        setTab(tabIndex) {
            sessionStorage.setItem('tab', tabIndex)
        },
        getTab() {
            this.tab = sessionStorage.getItem('tab')
        },
        restoreApplicationFromStorage() {
            this.tab = sessionStorage.getItem('tab')
            this.selectedGameIndexAllGames = sessionStorage.getItem('allGamesView')
            this.selectedGameIndexWishlist = sessionStorage.getItem('wishlistView')
        }
    }
}

</script>

<template>
    <div id="frame">
        <h1>Computer Games Wishlist</h1>
        <v-card>
            <v-tabs fixed-tabs v-model="tab" bg-color="blue">
                <v-tab :value="0" @click="setTab(0)">All Games</v-tab>
                <v-tab :value="1" @click="setTab(1)">Wishlist</v-tab>
                <v-tab :value="2" @click="setTab(2)">Legal Notice</v-tab>
            </v-tabs>
            <v-window v-model="tab">
                <v-window-item :value="0">
                    <div v-show="selectedViewAllGames == 0">
                        <GamesList :games="gamesArray" @viewGameFromAllGames="showGameFromList"
                            @addToWishlist="addToWishlist">
                        </GamesList>
                    </div>
                    <div v-show="selectedViewAllGames == 1">
                        <SingleGame @returnToList="showListAllGames" :gameIndex="selectedGameIndexAllGames"
                            :games="gamesArray">
                        </SingleGame>
                    </div>
                </v-window-item>
                <v-window-item :value="1">
                    <div v-show="selectedViewWishlist == 0">
                        <WishList :wishlist="wishlistArray" @viewGameFromWishlist="showGameFromWishlist"
                            @deleteFromWishlist="removeFromWishlist"></WishList>
                    </div>
                    <div v-show="selectedViewWishlist == 1">
                        <SingleGame @returnToList="showListWishlist" :gameIndex="selectedGameIndexWishlist"
                            :games="gamesArray"></SingleGame>
                    </div>
                </v-window-item>
                <v-window-item :value="2">
                    <div id="legalNoticeTab">
                        <div id="page">
                            
                        </div>
                    </div>
                </v-window-item>
            </v-window>
        </v-card>
    </div>
</template>

<style scoped>
* {
    background-color: #0D47A1;
    font-family: Arial;
}

v-tabs {
    width: 100%;
}


h1 {
    text-align: center;
    padding: 1%;
    color: white;
}

#legalNoticeTab {
    height: 967px;
}

#page {
    background-color: lightblue;
    width: 60%;
    height: 95%;
    margin-left: auto;
    margin-right: auto;
}
</style>
